### ISSUE TITLE
Wagon checklist

### ISSUE THREAD

**Issue by ckn07** [ckn07/mind-the-map#152]
- [ ] Open Graph meta tags are properly set
- [ ] 404 and 500 pages are customized
- [ ] og:image has the right dimensions (1200x630)
